export default [
  { label: 'Afganistán', value: '+93', ISO: 'AF' },
  { label: 'Albania', value: '+355', ISO: 'AL' },
  { label: 'Alemania', value: '+49', ISO: 'DE' },
  { label: 'Andorra', value: '+376', ISO: 'AD' },
  { label: 'Angola', value: '+244', ISO: 'AO' },
  { label: 'Anguila', value: '+1264', ISO: 'AI' },
  { label: 'Antártida', value: '+672', ISO: 'AQ' },
  { label: 'Antigua y Barbuda', value: '+1268', ISO: 'AG' },
  { label: 'Antillas Neerlandesas', value: '+599', ISO: 'AN' },
  { label: 'Arabia Saudita', value: '+966', ISO: 'SA' },
  { label: 'Argelia', value: '+213', ISO: 'DZ' },
  { label: 'Argentina', value: '+54', ISO: 'AR' },
  { label: 'Armenia', value: '+374', ISO: 'AM' },
  { label: 'Aruba', value: '+297', ISO: 'AW' },
  { label: 'Australia', value: '+61', ISO: 'AU' },
  { label: 'Austria', value: '+43', ISO: 'AT' },
  { label: 'Azerbaiyán', value: '+994', ISO: 'AZ' },
  { label: 'Bahamas', value: '+1242', ISO: 'BS' },
  { label: 'Bahréin', value: '+973', ISO: 'BH' },
  { label: 'Bangladesh', value: '+880', ISO: 'BD' },
  { label: 'Barbados', value: '+1246', ISO: 'BB' },
  { label: 'Bélgica', value: '+32', ISO: 'BE' },
  { label: 'Belice', value: '+501', ISO: 'BZ' },
  { label: 'Benin', value: '+229', ISO: 'BJ' },
  { label: 'Bermudas', value: '+1441', ISO: 'BM' },
  { label: 'Bután', value: '+975', ISO: 'BT' },
  { label: 'Bielorrusia', value: '+375', ISO: 'BY' },
  { label: 'Bolivia', value: '+591', ISO: 'BO' },
  {
    label: 'Bonaire, Saint Eustatius And Saba',
    value: '+599',
    ISO: 'BQ',
  },
  { label: 'Bosnia y Herzegovina', value: '+387', ISO: 'BA' },
  { label: 'Botsuana', value: '+267', ISO: 'BW' },
  { label: 'Brasil', value: '+55', ISO: 'BR' },
  { label: 'Brunéi', value: '+673', ISO: 'BN' },
  { label: 'Bulgaria', value: '+359', ISO: 'BG' },
  { label: 'Burkina Faso', value: '+226', ISO: 'BF' },
  { label: 'Burundi', value: '+257', ISO: 'BI' },
  { label: 'Cabo Verde', value: '+238', ISO: 'CV' },
  { label: 'Camboya', value: '+855', ISO: 'KH' },
  { label: 'Camerún', value: '+237', ISO: 'CM' },
  { label: 'Canadá', value: '+1', ISO: 'CA' },
  { label: 'Chad', value: '+235', ISO: 'TD' },
  { label: 'Chile', value: '+56', ISO: 'CL' },
  { label: 'China', value: '+86', ISO: 'CN' },
  { label: 'Chipre', value: '+357', ISO: 'CY' },
  { label: 'Ciudad del Vaticano', value: '+39', ISO: 'VA' },
  { label: 'Colombia', value: '+57', ISO: 'CO' },
  { label: 'Comoras', value: '+269', ISO: 'KM' },
  { label: 'Congo', value: '+242', ISO: 'CG' },
  { label: 'República Democrática del Congo', value: '+243', ISO: 'CD' },
  { label: 'Corea del Norte', value: '+850', ISO: 'KP' },
  { label: 'Corea del Sur', value: '+82', ISO: 'KR' },
  { label: 'Costa de Marfil', value: '+225', ISO: 'CI' },
  { label: 'Costa Rica', value: '+506', ISO: 'CR' },
  { label: 'Croacia', value: '+385', ISO: 'HR' },
  { label: 'Cuba', value: '+53', ISO: 'CU' },
  { label: 'Curaçao', value: '+599', ISO: 'CW' },
  { label: 'Dinamarca', value: '+45', ISO: 'DK' },
  { label: 'Domínica', value: '+1767', ISO: 'DM' },
  { label: 'Ecuador', value: '+593', ISO: 'EC' },
  { label: 'Egipto', value: '+20', ISO: 'EG' },
  { label: 'El Salvador', value: '+503', ISO: 'SV' },
  { label: 'Emiratos Árabes Unidos', value: '+971', ISO: 'AE' },
  { label: 'Eritrea', value: '+291', ISO: 'ER' },
  { label: 'Eslovaquia', value: '+421', ISO: 'SK' },
  { label: 'Eslovenia', value: '+386', ISO: 'SI' },
  { label: 'España', value: '+34', ISO: 'ES' },
  { label: 'Estados Unidos de América', value: '+1', ISO: 'US' },
  { label: 'Estonia', value: '+372', ISO: 'EE' },
  { label: 'Etiopía', value: '+251', ISO: 'ET' },
  { label: 'Fiji', value: '+679', ISO: 'FJ' },
  { label: 'Filipinas', value: '+63', ISO: 'PH' },
  { label: 'Finlandia', value: '+358', ISO: 'FI' },
  { label: 'Francia', value: '+33', ISO: 'FR' },
  { label: 'Gabón', value: '+241', ISO: 'GA' },
  { label: 'Gambia', value: '+220', ISO: 'GM' },
  { label: 'Georgia', value: '+995', ISO: 'GE' },
  {
    label: 'Georgia del Sur e Islas Sandwich del Sur',
    value: '+995',
    ISO: 'GS',
  },
  { label: 'South Sudan', value: '+211', ISO: 'SS' },
  { label: 'Ghana', value: '+233', ISO: 'GH' },
  { label: 'Gibraltar', value: '+350', ISO: 'GI' },
  { label: 'Granada', value: '+1473', ISO: 'GD' },
  { label: 'Grecia', value: '+30', ISO: 'GR' },
  { label: 'Groenlandia', value: '+299', ISO: 'GL' },
  { label: 'Guadalupe', value: '+590', ISO: 'GP' },
  { label: 'Guam', value: '+1671', ISO: 'GU' },
  { label: 'Guatemala', value: '+502', ISO: 'GT' },
  { label: 'Guayana', value: '+594', ISO: 'GY' },
  { label: 'Guayana Francesa', value: '+594', ISO: 'GF' },
  { label: 'Guernsey', value: '+44', ISO: 'GG' },
  { label: 'Guinea', value: '+224', ISO: 'GN' },
  { label: 'Guinea-Bissau', value: '+245', ISO: 'GW' },
  { label: 'Guinea Ecuatorial', value: '+240', ISO: 'GQ' },
  { label: 'Haití', value: '+509', ISO: 'HT' },
  { label: 'Honduras', value: '+504', ISO: 'HN' },
  { label: 'Hong Kong', value: '+852', ISO: 'HK' },
  { label: 'Hungría', value: '+36', ISO: 'HU' },
  { label: 'India', value: '+91', ISO: 'IN' },
  { label: 'Indonesia', value: '+62', ISO: 'ID' },
  { label: 'Irán', value: '+98', ISO: 'IR' },
  { label: 'Iraq', value: '+964', ISO: 'IQ' },
  { label: 'Irlanda', value: '+353', ISO: 'IE' },
  { label: 'Isla Bouvet', value: '+47', ISO: 'BV' },
  { label: 'Isla de Man', value: '+44', ISO: 'IM' },
  { label: 'Islandia', value: '+354', ISO: 'IS' },
  { label: 'Islas Áland', value: '+358', ISO: 'AX' },
  { label: 'Islas Caimán', value: '+1345', ISO: 'KY' },
  { label: 'Islas Christmas', value: '+61', ISO: 'CX' },
  { label: 'Islas Cocos', value: '+61', ISO: 'CC' },
  { label: 'Islas Cook', value: '+682', ISO: 'CK' },
  { label: 'Islas Faroe', value: '+298', ISO: 'FO' },
  { label: 'Islas Heard y McDonald', value: '+61', ISO: 'HM' },
  { label: 'Islas Malvinas', value: '+500', ISO: 'FK' },
  { label: 'Islas Marshall', value: '+692', ISO: 'MH' },
  { label: 'Islas Norkfolk', value: '+672', ISO: 'NF' },
  { label: 'Islas Palaos', value: '+680', ISO: 'PW' },
  { label: 'Islas Pitcairn', value: '+870', ISO: 'PN' },
  { label: 'Islas Solomón', value: '+677', ISO: 'SB' },
  { label: 'Islas Svalbard y Jan Mayen', value: '+47 79', ISO: 'SJ' },
  { label: 'Islas Turcas y Caicos', value: '+1649', ISO: 'TC' },
  {
    label: 'Islas Ultramarinas de Estados Unidos',
    value: '+1',
    ISO: 'UM',
  },
  { label: 'Islas Vírgenes Británicas', value: '+1284', ISO: 'VG' },
  { label: 'Wake Island', value: '+1808', ISO: 'WK' },
  {
    label: 'Islas Vírgenes de los Estados Unidos de América',
    value: '+1340',
    ISO: 'VI',
  },
  { label: 'Israel', value: '+972', ISO: 'IL' },
  { label: 'Italia', value: '+39', ISO: 'IT' },
  { label: 'Jamaica', value: '+1876', ISO: 'JM' },
  { label: 'Japón', value: '+81', ISO: 'JP' },
  { label: 'Jersey', value: '+44', ISO: 'JE' },
  { label: 'Jordania', value: '+962', ISO: 'JO' },
  { label: 'Kazajstán', value: '+7', ISO: 'KZ' },
  { label: 'Kenia', value: '+254', ISO: 'KE' },
  { label: 'Kirguistán', value: '+996', ISO: 'KG' },
  { label: 'Kiribati', value: '+686', ISO: 'KI' },
  { label: 'Kuwait', value: '+965', ISO: 'KW' },
  { label: 'Laos', value: '+856', ISO: 'LA' },
  { label: 'Lesotho', value: '+266', ISO: 'LS' },
  { label: 'Letonia', value: '+371', ISO: 'LV' },
  { label: 'Líbano', value: '+961', ISO: 'LB' },
  { label: 'Liberia', value: '+231', ISO: 'LR' },
  { label: 'Libia', value: '+218', ISO: 'LY' },
  { label: 'Liechtenstein', value: '+423', ISO: 'LI' },
  { label: 'Lituania', value: '+370', ISO: 'LT' },
  { label: 'Luxemburgo', value: '+352', ISO: 'LU' },
  { label: 'Macao', value: '+853', ISO: 'MO' },
  { label: 'Macedonia', value: '+389', ISO: 'MK' },
  { label: 'Madagascar', value: '+261', ISO: 'MG' },
  { label: 'Malasia', value: '+60', ISO: 'MY' },
  { label: 'Malawi', value: '+265', ISO: 'MW' },
  { label: 'Maldivas', value: '+960', ISO: 'MV' },
  { label: 'Mali', value: '+223', ISO: 'ML' },
  { label: 'Malta', value: '+356', ISO: 'MT' },
  { label: 'Marruecos', value: '+212', ISO: 'MA' },
  { label: 'Martinica', value: '+596', ISO: 'MQ' },
  { label: 'Mauricio', value: '+230', ISO: 'MU' },
  { label: 'Mauritania', value: '+222', ISO: 'MR' },
  { label: 'Mayotte', value: '+262', ISO: 'YT' },
  { label: 'México', value: '+52', ISO: 'MX' },
  { label: 'Micronesia', value: '+691', ISO: 'FM' },
  { label: 'Midway Islands', value: '+1808', ISO: 'MI' },
  { label: 'Moldova', value: '+373', ISO: 'MD' },
  { label: 'Mónaco', value: '+377', ISO: 'MC' },
  { label: 'Mongolia', value: '+976', ISO: 'MN' },
  { label: 'Montenegro', value: '+382', ISO: 'ME' },
  { label: 'Montserrat', value: '+1664', ISO: 'MS' },
  { label: 'Mozambique', value: '+258', ISO: 'MZ' },
  { label: 'Myanmar', value: '+95', ISO: 'MM' },
  { label: 'Namibia', value: '+264', ISO: 'NA' },
  { label: 'Nauru', value: '+674', ISO: 'NR' },
  { label: 'Nepal', value: '+977', ISO: 'NP' },
  { label: 'Nicaragua', value: '+505', ISO: 'NI' },
  { label: 'Níger', value: '+227', ISO: 'NE' },
  { label: 'Nigeria', value: '+234', ISO: 'NG' },
  { label: 'Niue', value: '+683', ISO: 'NU' },
  { label: 'Islas Marianas', value: '+1670', ISO: 'MP' },
  { label: 'Noruega', value: '+47', ISO: 'NO' },
  { label: 'Nueva Caledonia', value: '+687', ISO: 'NC' },
  { label: 'Nueva Zelanda', value: '+64', ISO: 'NZ' },
  { label: 'Omán', value: '+968', ISO: 'OM' },
  { label: 'Países Bajos', value: '+31', ISO: 'NL' },
  { label: 'Pakistán', value: '+92', ISO: 'PK' },
  { label: 'Palestina', value: '+970', ISO: 'PS' },
  { label: 'Panamá', value: '+507', ISO: 'PA' },
  { label: 'Papúa Nueva Guinea', value: '+675', ISO: 'PG' },
  { label: 'Paraguay', value: '+595', ISO: 'PY' },
  { label: 'Perú', value: '+51', ISO: 'PE' },
  { label: 'Polinesia Francesa', value: '+689', ISO: 'PF' },
  { label: 'Polonia', value: '+48', ISO: 'PL' },
  { label: 'Portugal', value: '+351', ISO: 'PT' },
  { label: 'Puerto Rico', value: '+1', ISO: 'PR' },
  { label: 'Qatar', value: '+974', ISO: 'QA' },
  { label: 'Reino Unido', value: '+44', ISO: 'GB' },
  { label: 'República Centro-Africana', value: '+236', ISO: 'CF' },
  { label: 'República Checa', value: '+420', ISO: 'CZ' },
  { label: 'Serbia', value: '+381', ISO: 'RS' },
  { label: 'República Dominicana', value: '+1809', ISO: 'DO' },
  { label: 'Reunión', value: '+262', ISO: 'RE' },
  { label: 'Ruanda', value: '+250', ISO: 'RW' },
  { label: 'Rumanía', value: '+40', ISO: 'RO' },
  { label: 'Rusia', value: '+7', ISO: 'RU' },
  { label: 'Sahara Occidental', value: '+212', ISO: 'EH' },
  { label: 'Samoa', value: '+685', ISO: 'WS' },
  { label: 'Samoa Americana', value: '+1684', ISO: 'AS' },
  { label: 'San Bartolomé', value: '+590', ISO: 'BL' },
  { label: 'San Cristóbal y Nieves', value: '+1869', ISO: 'KN' },
  { label: 'San Martín', value: '+590', ISO: 'MF' },
  { label: 'San Marino', value: '+378', ISO: 'SM' },
  { label: 'San Pedro y Miquelón', value: '+508', ISO: 'PM' },
  { label: 'Santa Elena', value: '+290', ISO: 'SH' },
  { label: 'Santa Lucía', value: '+1758', ISO: 'LC' },
  { label: 'Santo Tomé y Príncipe', value: '+239', ISO: 'ST' },
  { label: 'San Vicente y las Granadinas', value: '+1784', ISO: 'VC' },
  { label: 'Senegal', value: '+221', ISO: 'SN' },
  { label: 'Seychelles', value: '+248', ISO: 'SC' },
  { label: 'Sierra Leona', value: '+232', ISO: 'SL' },
  { label: 'Singapur', value: '+65', ISO: 'SG' },
  { label: 'Sint Maarten (Dutch part)', value: '+1', ISO: 'SX' },
  { label: 'Siria', value: '+963', ISO: 'SY' },
  { label: 'Somalia', value: '+252', ISO: 'SO' },
  { label: 'Sri Lanka', value: '+94', ISO: 'LK' },
  { label: 'Suazilandia', value: '+268', ISO: 'SZ' },
  { label: 'Sudáfrica', value: '+27', ISO: 'ZA' },
  { label: 'Sudán', value: '+249', ISO: 'SD' },
  { label: 'Suecia', value: '+46', ISO: 'SE' },
  { label: 'Suiza', value: '+41', ISO: 'CH' },
  { label: 'Surinam', value: '+597', ISO: 'SR' },
  { label: 'Tailandia', value: '+66', ISO: 'TH' },
  { label: 'Taiwán', value: '+886', ISO: 'TW' },
  { label: 'Tanzania', value: '+255', ISO: 'TZ' },
  { label: 'Tayikistán', value: '+992', ISO: 'TJ' },
  {
    label: 'Territorio Británico del Océano Índico',
    value: '+246',
    ISO: 'IO',
  },
  { label: 'Territorios Australes Franceses', value: '+262', ISO: 'TF' },
  { label: 'Timor-Leste', value: '+670', ISO: 'TL' },
  { label: 'Togo', value: '+228', ISO: 'TG' },
  { label: 'Tokelau', value: '+690', ISO: 'TK' },
  { label: 'Tonga', value: '+676', ISO: 'TO' },
  { label: 'Trinidad y Tobago', value: '+1868', ISO: 'TT' },
  { label: 'Túnez', value: '+216', ISO: 'TN' },
  { label: 'Turkmenistán', value: '+993', ISO: 'TM' },
  { label: 'Turquía', value: '+90', ISO: 'TR' },
  { label: 'Tuvalu', value: '+688', ISO: 'TV' },
  { label: 'Ucrania', value: '+380', ISO: 'UA' },
  { label: 'Uganda', value: '+256', ISO: 'UG' },
  { label: 'Uruguay', value: '+598', ISO: 'UY' },
  { label: 'Uzbekistán', value: '+998', ISO: 'UZ' },
  { label: 'Vanuatu', value: '+678', ISO: 'VU' },
  { label: 'Venezuela', value: '+58', ISO: 'VE' },
  { label: 'Vietnam', value: '+84', ISO: 'VN' },
  { label: 'Wallis y Futuna', value: '+681', ISO: 'WF' },
  { label: 'Yemen', value: '+967', ISO: 'YE' },
  { label: 'Yibuti', value: '+253', ISO: 'DJ' },
  { label: 'Zambia', value: '+260', ISO: 'ZM' },
  { label: 'Zimbabwe', value: '+263', ISO: 'ZW' },
]
